# Jekyll configuration
title: "Hi there, I'm Sue GC"
url: 'http://suelengc.github.io'
author: Suelen GC
twitter: 'suelengc'
github: 'suelengc'
email: 'suelengcarvalho@gmail'
description: 'Mobile development, web development stuffs, tutorials for beginners and more by Suelen GC'

category_title_prefix: ''
category_dir: /

# Basic configuration
permalink: /:year/:title/
destination: ./_publish

# Use Pygments to highlight code blocks
baseurl: '/'
highlighter: pygments
paginate: 10
exclude: ['/node_modules', '/.gitignore', './config.ru', './Gemfile', './Gemfile.lock', './CNAME', '/gulpfile.js', '/package.json', '/README.md', '/src']

# Publish posts with future date.
future: false

# Compile posts in the _drafts directory.
show_drafts: false

gems: ['jekyll-paginate']
