# Jekyll configuration
title: "Hi there, I'm Rafaell"
url: 'http://rafaell-lycan.com'
author: Rafaell Lycan
twitter: 'RafaellLycan'
github: 'rafaell-lycan'
email: 'sonny.webdsg@gmail'
description: 'Web development, front end stuff, tutorials for beginners and more by Rafaell Lycan'

category_title_prefix: ''
category_dir: /

# Basic configuration
permalink: /:year/:title/
destination: ./_publish

# Use Pygments to highlight code blocks
baseurl: '/'
highlighter: pygments
paginate: 10
exclude: ['/node_modules', '/.gitignore', './CNAME', '/Gruntfile.js', '/package.json', '/README.md', '/src']

# Publish posts with future date.
future: true

# Compile posts in the _drafts directory.
show_drafts: false
