name: Rafaell Lycan
author: Rafaell Lycan
markdown: redcarpet
# permalink: :title
permalink: /blog/:title
pygments: true
future: true
destination: ./_publish
paginate: 10
baseurl: '/'
sitemap:
   file: "/sitemap.xml"
exclude: ["/node_modules","/.gitignore","./CNAME","/Gruntfile.js","/package.json","/README.md"]